on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*

jobs:

  set-version:
    name: Set Version
    uses: ./.github/workflows/job-set-version.yml

  build-github:
    name: Build Package for GitHub Registry
    needs: set-version
    uses: ./.github/workflows/job-build-package.yml
    with:
      overwrite-publish-config: "https://npm.pkg.github.com/@$GITHUB_REPOSITORY_OWNER"
      artifact-name: github-npm-package

  build-npm:
    name: Build Package for NPM Registry
    needs: set-version
    uses: ./.github/workflows/job-build-package.yml

  deploy-github:
    name: Deploy Package to GitHub Registry
    needs: build-github
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/job-deploy-package.yml
    with:
      registry-url: 'https://npm.pkg.github.com'
      artifact-name: github-npm-package
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-npm:
    name: Deploy Package to NPM Registry
    needs: [build-npm, deploy-github]
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/job-deploy-package.yml
    secrets:
      access-token: ${{ secrets.NPM_TOKEN }}

  deploy-pre-release-assets:
    name: Deploy Assets to GitHub Release
    if: github.ref != 'refs/heads/main'
    needs: [set-version, build-npm]
    permissions:
      contents: write
    uses: ./.github/workflows/job-github-release.yml
    with:
      tag: ${{ needs.set-version.outputs.version }}
      is-pre-release: true

  deploy-release-assets:
    name: Deploy Assets to GitHub Release
    if: github.ref == 'refs/heads/main'
    needs: [set-version, build-npm]
    permissions:
      contents: write
    uses: ./.github/workflows/job-github-release.yml
    with:
      tag: ${{ needs.set-version.outputs.version }}